# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-05 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_addition'),
        ('catalog', '0001_auto_20190123_1927'),
    ]

    operations = [
    ]
