# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-03-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20190305_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageurl',
            field=models.URLField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turker',
            name='turkerid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
