# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-06 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='ann_cat',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
