# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_actions_ann_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='ann_clr',
            field=models.CharField(default='C', max_length=1),
        ),
    ]
