# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-13 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_actions_ann_clr'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ann_rnd',
            field=models.CharField(default='r00', max_length=3),
        ),
    ]
