# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-01-23 19:09
from __future__ import unicode_literals

from django.db import migrations
import random
from django.utils import timezone
from collections import defaultdict


def create_initial_annotations(apps, schema_editor):
  Image = apps.get_model('catalog', 'Image')

  image_list = []
  for line in open("/projects1/refer_backend/refer360annotation/PANOLIST"):
    image_category = line.strip()
    for pano_meta in open(image_category, 'r'):
      category = pano_meta.strip().split('/')[2]
      panoid = pano_meta.strip().split('/')[3].split('.')[0].split('_')[1]
      image_list.append(panoid + "_" + category + '.jpg')
  print(">>>", len(image_list))
  images = []

  for prefix in image_list:
    imageurl = "https://s3.amazonaws.com/refer360/sun360images_4552x2276/pano_" + prefix
    print(imageurl)
    image = Image(imageurl=imageurl,
                  date=timezone.now())
    image.save()


class Migration(migrations.Migration):

  dependencies = [
      ('catalog', '0001_initial'),
  ]

  operations = [
      migrations.RunPython(create_initial_annotations),

  ]
