# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

  initial = True

  dependencies = [
  ]

  operations = [

      migrations.CreateModel(
          name='Image',
          fields=[
              ('date', models.DateTimeField(auto_now_add=True)),
              ('imageurl', models.URLField(primary_key=True,
                                           serialize=False, verbose_name='imageurl')),
          ],
      ),
      migrations.CreateModel(
          name='Turker',
          fields=[
              ('date', models.DateTimeField(auto_now_add=True)),
              ('turkerid', models.CharField(max_length=100, primary_key=True,
                                            serialize=False, verbose_name='turkerid')),
          ],
      ),
      migrations.CreateModel(
          name='Feedback',
          fields=[
              ('date', models.DateTimeField(auto_now_add=True)),
              ('feedback_text', models.CharField(max_length=50, primary_key=True,
                                                 serialize=False, verbose_name='feedback_text')),
              ('feedback_detail', models.CharField(
                  max_length=10000, verbose_name='feedback_detail')),
              ('validation', models.IntegerField(
                  verbose_name='validation')),
          ],
      ),
      migrations.CreateModel(
          name='Annotation',
          fields=[
              ('id', models.AutoField(auto_created=True,
                                      primary_key=True, serialize=False, verbose_name='ID')),
              ('date', models.DateTimeField(auto_now_add=True)),
              ('refexp', models.CharField(max_length=700)),
              #('ann_cat', models.CharField(max_length=1)),
              ('latitude', models.FloatField()),
              ('longitude', models.FloatField()),
              ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                          related_name='annotations', to='catalog.Image')),
              ('turker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='annotations', to='catalog.Turker')),
              ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='annotations', to='catalog.Feedback')),
          ],
      ),
      migrations.CreateModel(
          name='Actions',
          fields=[
              ('id', models.AutoField(auto_created=True,
                                      primary_key=True, serialize=False, verbose_name='ID')),
              ('date', models.DateTimeField(auto_now_add=True)),
              ('action_list', models.CharField(
                  max_length=10000, verbose_name='actions_list')),
              ('pred_latitude', models.FloatField()),
              ('pred_longitude', models.FloatField()),
              ('start_latitude', models.FloatField()),
              ('start_longitude', models.FloatField()),
              ('turker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='actions', to='catalog.Turker')),
              ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='actions', to='catalog.Annotation')),
              ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='annotations', to='catalog.Feedback')),
          ],
      ),


  ]
